# Generated by Django 3.0.9 on 2020-08-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_community',
            name='image',
        ),
        migrations.RemoveField(
            model_name='card_player',
            name='image',
        ),
    ]
