# Generated by Django 3.0.8 on 2020-07-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rank',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.CharField(default='', max_length=2),
        ),
    ]
