# Generated by Django 3.0.8 on 2020-07-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_auto_20200729_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rank',
            field=models.CharField(default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.CharField(default='', max_length=2, null=True),
        ),
    ]
