# Generated by Django 3.1 on 2020-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_auto_20200804_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='total_pot_currency',
        ),
        migrations.AlterField(
            model_name='game',
            name='total_pot',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
