# Generated by Django 3.1 on 2020-08-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_auto_20200810_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stack_currency',
        ),
        migrations.AlterField(
            model_name='player',
            name='stack',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
