# Generated by Django 3.1 on 2020-08-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0005_auto_20200811_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='game', to='poker.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_pot',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='stack',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
