# Generated by Django 3.1 on 2020-08-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_auto_20200811_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='game', to='poker.Player'),
        ),
    ]
